#!/usr/bin/env python3
"""Hand-written Unitree G1 walking controller in MuJoCo.

The controller deliberately does not change the downloaded robot model: actuator
parameters, joint damping, ctrl ranges, body inertias, and contacts are taken
from the XML exactly as loaded.  It also never writes qfrc_applied/xfrc_applied
or teleports the floating base during simulation.  All motion is generated by
sending joint-position set-points to the model's default position actuators.

The gait is a small-amplitude Raibert-style oscillator with torso attitude and
lateral capture feedback.  It is intentionally conservative so that the robot
balances itself for the whole clip instead of relying on artificial external
forces.
"""
from __future__ import annotations

import argparse
import json
import math
from dataclasses import dataclass, asdict
from pathlib import Path

import imageio.v2 as imageio
import mujoco
import numpy as np


DEFAULT_MODEL = Path("models/mujoco_menagerie/unitree_g1/scene.xml")


@dataclass(frozen=True)
class GaitParams:
    # Hand-tuned stable gait parameters.  target_speed is used by the capture
    # feedback; the achieved velocity depends on the passive/contact dynamics.
    target_speed: float = 0.5
    frequency_hz: float = 1.2960921558296645
    hip_swing: float = 0.0954761506847576
    knee_base: float = 0.23165021209654055
    knee_swing: float = 0.119735610008505
    hip_bias: float = -0.013657651013218863
    lateral_shift: float = 0.11010972085365418
    velocity_gain: float = 0.09020069575951398
    pitch_gain: float = 0.2861563370537825
    roll_hip_gain: float = 0.5076319119415711
    roll_rate_hip_gain: float = -0.09576991047256994
    roll_ankle_gain: float = -0.3196651435132898
    roll_rate_ankle_gain: float = -0.011928052693877866
    ankle_knee_coupling: float = 0.5889311970340689
    toe_pitch: float = -0.10888728617797443
    ramp_start_s: float = 0.2
    ramp_duration_s: float = 1.0


class G1Walker:
    def __init__(self, model_path: Path, params: GaitParams):
        self.model_path = model_path
        self.params = params
        self.model = mujoco.MjModel.from_xml_path(str(model_path))
        self.data = mujoco.MjData(self.model)

        if self.model.nkey < 1:
            raise RuntimeError("Expected the downloaded G1 scene to provide a standing keyframe.")
        mujoco.mj_resetDataKeyframe(self.model, self.data, 0)

        self.act_names = [
            mujoco.mj_id2name(self.model, mujoco.mjtObj.mjOBJ_ACTUATOR, i)
            for i in range(self.model.nu)
        ]
        self.a = {name: i for i, name in enumerate(self.act_names)}
        self.stand_ctrl = self.model.key_ctrl[0].copy()
        self.pelvis_id = mujoco.mj_name2id(self.model, mujoco.mjtObj.mjOBJ_BODY, "pelvis")

        # Verify that this controller has not modified the actuator defaults.
        self.actuator_signature = {
            "ctrlrange": self.model.actuator_ctrlrange.copy().tolist(),
            "gainprm_first3": self.model.actuator_gainprm[:, :3].copy().tolist(),
            "biasprm_first3": self.model.actuator_biasprm[:, :3].copy().tolist(),
        }

    def pitch_roll(self) -> tuple[float, float]:
        """Return pelvis pitch and roll in radians from the body rotation matrix."""
        rot = self.data.xmat[self.pelvis_id].reshape(3, 3)
        pitch = math.asin(float(np.clip(-rot[2, 0], -1.0, 1.0)))
        roll = math.atan2(float(rot[2, 1]), float(rot[2, 2]))
        return pitch, roll

    def control(self) -> np.ndarray:
        p = self.params
        t = self.data.time
        ctrl = self.stand_ctrl.copy()
        pitch, roll = self.pitch_roll()
        vx = float(self.data.qvel[0])
        pitch_rate = float(self.data.qvel[4])
        roll_rate = float(self.data.qvel[3])

        ramp = np.clip((t - p.ramp_start_s) / p.ramp_duration_s, 0.0, 1.0)
        phase_global = 2.0 * math.pi * p.frequency_hz * t

        # Capture feedback: positive if the robot is behind the requested speed;
        # negative if it pitches forward or moves too fast.
        lean = np.clip(
            -p.pitch_gain * pitch - 0.05 * pitch_rate + p.velocity_gain * (p.target_speed - vx),
            -0.16,
            0.16,
        )

        # Lateral balance.  A common hip-roll offset shifts the pelvis toward the
        # stance foot; roll-rate terms damp side falls.
        support_wave = math.sin(phase_global)
        lateral = np.clip(
            -p.lateral_shift * support_wave
            + p.roll_hip_gain * roll
            + p.roll_rate_hip_gain * roll_rate,
            -0.22,
            0.22,
        )

        for side, phase_offset in (("left", 0.0), ("right", math.pi)):
            phase = phase_global + phase_offset
            s = math.sin(phase)
            swing = max(0.0, -s)
            # Smooth swing knee flexion; zero in stance, bell-shaped in swing.
            lift = math.sin(math.pi * swing) if swing > 0.0 else 0.0

            hip = p.hip_bias - p.hip_swing * s + lean
            knee = p.knee_base + p.knee_swing * lift
            ankle = -hip - p.ankle_knee_coupling * knee + p.toe_pitch * s - 0.10 * lean

            ctrl[self.a[f"{side}_hip_pitch_joint"]] = hip
            ctrl[self.a[f"{side}_knee_joint"]] = knee
            ctrl[self.a[f"{side}_ankle_pitch_joint"]] = ankle
            ctrl[self.a[f"{side}_hip_roll_joint"]] = lateral
            ctrl[self.a[f"{side}_ankle_roll_joint"]] = np.clip(
                -0.50 * lateral + p.roll_ankle_gain * roll + p.roll_rate_ankle_gain * roll_rate,
                -0.25,
                0.25,
            )
            ctrl[self.a[f"{side}_hip_yaw_joint"]] = 0.0

        # Torso and arms provide small, compliant counter-motion.  These are joint
        # targets only; no base forces or state correction are applied.
        ctrl[self.a["waist_pitch_joint"]] = np.clip(-0.50 * pitch - 0.05 * pitch_rate, -0.20, 0.20)
        ctrl[self.a["waist_roll_joint"]] = np.clip(-0.50 * roll - 0.05 * roll_rate, -0.20, 0.20)
        arm = 0.22 * math.sin(phase_global)
        ctrl[self.a["left_shoulder_pitch_joint"]] = 0.20 - arm
        ctrl[self.a["right_shoulder_pitch_joint"]] = 0.20 + arm

        # Blend from the XML stand keyframe and respect the XML ctrlrange exactly.
        ctrl = self.stand_ctrl + ramp * (ctrl - self.stand_ctrl)
        return np.clip(ctrl, self.model.actuator_ctrlrange[:, 0], self.model.actuator_ctrlrange[:, 1])

    def step(self) -> None:
        self.data.ctrl[:] = self.control()
        # Explicitly keep external force arrays zero.  This is the default, but
        # keeping it here makes the safety invariant auditable.
        self.data.qfrc_applied[:] = 0.0
        self.data.xfrc_applied[:] = 0.0
        mujoco.mj_step(self.model, self.data)


def render_video(
    walker: G1Walker,
    duration: float,
    out_path: Path,
    width: int,
    height: int,
    fps: int,
) -> dict:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    renderer = mujoco.Renderer(walker.model, width=width, height=height)
    camera = mujoco.MjvCamera()
    camera.type = mujoco.mjtCamera.mjCAMERA_TRACKING
    camera.trackbodyid = walker.pelvis_id
    camera.distance = 3.0
    camera.azimuth = 155.0
    camera.elevation = -16.0
    camera.lookat[:] = [0.0, 0.0, 0.75]

    dt = walker.model.opt.timestep
    steps = int(round(duration / dt))
    frame_count = int(round(duration * fps))
    next_frame_index = 0

    start_x = float(walker.data.qpos[0])
    max_abs_external = 0.0
    min_height = float("inf")
    max_abs_pitch = 0.0
    max_abs_roll = 0.0

    with imageio.get_writer(out_path, fps=fps, macro_block_size=1, codec="libx264", quality=8) as writer:
        for _step in range(steps):
            walker.step()
            pitch, roll = walker.pitch_roll()
            min_height = min(min_height, float(walker.data.qpos[2]))
            max_abs_pitch = max(max_abs_pitch, abs(pitch))
            max_abs_roll = max(max_abs_roll, abs(roll))
            max_abs_external = max(
                max_abs_external,
                float(np.max(np.abs(walker.data.qfrc_applied))) if walker.data.qfrc_applied.size else 0.0,
                float(np.max(np.abs(walker.data.xfrc_applied))) if walker.data.xfrc_applied.size else 0.0,
            )
            while next_frame_index < frame_count and walker.data.time >= next_frame_index / fps:
                camera.lookat[:] = [walker.data.qpos[0], walker.data.qpos[1], 0.75]
                renderer.update_scene(walker.data, camera=camera)
                frame = renderer.render()
                writer.append_data(frame)
                next_frame_index += 1

    end_x = float(walker.data.qpos[0])
    avg_speed = (end_x - start_x) / duration
    metrics = {
        "duration_s": duration,
        "video_width": width,
        "video_height": height,
        "fps": fps,
        "start_x_m": start_x,
        "end_x_m": end_x,
        "avg_forward_speed_mps": avg_speed,
        "final_forward_speed_mps": float(walker.data.qvel[0]),
        "min_pelvis_height_m": min_height,
        "max_abs_pitch_rad": max_abs_pitch,
        "max_abs_roll_rad": max_abs_roll,
        "max_abs_external_force_or_torque": max_abs_external,
        "model_path": str(walker.model_path),
        "actuator_signature": walker.actuator_signature,
        "gait_params": asdict(walker.params),
    }
    return metrics


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", type=Path, default=DEFAULT_MODEL)
    ap.add_argument("--duration", type=float, default=10.0)
    ap.add_argument("--output", type=Path, default=Path("artifacts/g1_walk_10s_640x480.mp4"))
    ap.add_argument("--width", type=int, default=640)
    ap.add_argument("--height", type=int, default=480)
    ap.add_argument("--fps", type=int, default=30)
    ap.add_argument("--metrics", type=Path, default=Path("artifacts/g1_walk_metrics.json"))
    args = ap.parse_args()

    walker = G1Walker(args.model, GaitParams())
    metrics = render_video(walker, args.duration, args.output, args.width, args.height, args.fps)
    args.metrics.parent.mkdir(parents=True, exist_ok=True)
    args.metrics.write_text(json.dumps(metrics, indent=2), encoding="utf-8")
    print(json.dumps({k: v for k, v in metrics.items() if k not in {"actuator_signature"}}, indent=2))
    print(f"video={args.output}")
    print(f"metrics={args.metrics}")


if __name__ == "__main__":
    main()
